TELEGRAM_TOKEN    = os.environ.get("TELEGRAM_TOKEN", "")
CHAT_ID           = os.environ.get("CHAT_ID", "1675630605")
TV_CHART_ID       = "jwwgzT2J"
TV_SNAPSHOT_URL   = f"https://www.tradingview.com/x/{TV_CHART_ID}/"
WEBHOOK_PORT      = int(os.environ.get("PORT", 8080))
WEBHOOK_SECRET    = "xqz_webhook_secret_2026"
BRIEFING_HOUR_WIB = 7
TIMEZONE          = "Asia/Jakarta"
SYMBOL            = "BTC/USDT"
OB_DIST_FIRE      = 0.5
OB_DIST_WATCH     = 1.5
QUANT_FIRE        = 9
QUANT_WATCH       = 7
NEWS_FIRE_HOURS   = 4
NEWS_WATCH_HOURS  = 24
